Document: vex
Title: Debian vex Manual
Author: <insert document author here>
Abstract: This manual describes what vex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vex/vex.sgml.gz

Format: postscript
Files: /usr/share/doc/vex/vex.ps.gz

Format: text
Files: /usr/share/doc/vex/vex.text.gz

Format: HTML
Index: /usr/share/doc/vex/html/index.html
Files: /usr/share/doc/vex/html/*.html

  
